# Generated by Django 2.2.1 on 2019-06-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakeitems',
            name='divString',
            field=models.TextField(blank=True),
        ),
    ]
